# NHANES Survey-Weighted Analysis Template
# Generated by NHANES to Lancet Platform

library(survey)
library(dplyr)

# Load data
data <- read.csv("analysis_data.csv")

# Declare survey design (single cycle)
design <- svydesign(
  id = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~WTMEC2YR,
  data = data,
  nest = TRUE
)

# For multiple cycles, adjust weights:
# data$WTMEC2YR_ADJ <- data$WTMEC2YR / n_cycles

# === Descriptive Statistics ===
# Weighted mean
svymean(~BMXBMI, design, na.rm = TRUE)

# Weighted median
svyquantile(~BMXBMI, design, quantiles = 0.5, na.rm = TRUE)

# Weighted frequency
svytable(~BPQ020, design)

# === Weighted Logistic Regression ===
model <- svyglm(
  BPQ020 ~ BMXBMI + RIDAGEYR + RIAGENDR + RIDRETH1 + DMDEDUC2 + INDFMPIR,
  design = design,
  family = quasibinomial
)

# Results
summary(model)

# Odds Ratios with 95% CI
exp(cbind(OR = coef(model), confint(model)))

# === Subgroup Analysis ===
# By sex
male_design <- subset(design, RIAGENDR == 1)
female_design <- subset(design, RIAGENDR == 2)

model_male <- svyglm(BPQ020 ~ BMXBMI + RIDAGEYR, design = male_design, family = quasibinomial)
model_female <- svyglm(BPQ020 ~ BMXBMI + RIDAGEYR, design = female_design, family = quasibinomial)

# === Table 1: Baseline Characteristics ===
library(tableone)
table1 <- svyCreateTableOne(
  vars = c("RIDAGEYR", "BMXBMI", "BPXSY1", "LBXTC", "DIQ010"),
  strata = "BPQ020",
  data = design,
  test = TRUE
)
print(table1, smd = TRUE)
