# NHANES Survival Analysis Template
# Generated by NHANES to Lancet Platform

library(survival)
library(survminer)
library(cmprsk)

# Load data
data <- read.csv("analysis_data.csv")

# === Kaplan-Meier Survival Analysis ===
surv_obj <- Surv(time = data$PERMTH_EXM, event = data$MORTSTAT)

# Fit KM model by diabetes status
km_fit <- survfit(surv_obj ~ data$DIQ010, data = data)

# Plot
ggsurvplot(
  km_fit,
  data = data,
  pval = TRUE,
  conf.int = TRUE,
  risk.table = TRUE,
  palette = "lancet",
  xlab = "Time (months)",
  ylab = "Survival Probability",
  title = "Kaplan-Meier Survival Curve by Diabetes Status"
)

# Log-rank test
survdiff(surv_obj ~ data$DIQ010, data = data)

# === Cox Proportional Hazards ===
cox_model <- coxph(
  Surv(PERMTH_EXM, MORTSTAT) ~ DIQ010 + RIDAGEYR + RIAGENDR + BMXBMI + BPXSY1,
  data = data
)
summary(cox_model)

# Hazard Ratios
exp(coef(cox_model))
exp(confint(cox_model))

# Proportional hazards assumption
cox.zph(cox_model)

# === Fine-Gray Competing Risk ===
# Recode: 0=censored, 1=CVD death, 2=non-CVD death
data$status_fg <- ifelse(data$UCOD_LEADING == "Diseases of heart", 1,
                  ifelse(data$MORTSTAT == 1, 2, 0))

fg_model <- crr(
  ftime = data$PERMTH_EXM,
  fstatus = data$status_fg,
  cov1 = model.matrix(~ DIQ010 + RIDAGEYR + RIAGENDR + BMXBMI - 1, data = data),
  failcode = 1,
  cencode = 0
)
summary(fg_model)
