"""
Survey-weighted R脚本生成器
NHANES复杂抽样设计统计分析

支持:
- svydesign() 调查设计声明
- svyglm() 加权回归
- svykm() 加权生存分析
- 加权基线特征表
- 加权Cox回归
- Fine-Gray竞争风险
- 亚组分析
- 森林图
"""

import os
import json
from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class AnalysisConfig:
    """分析配置"""
    analysis_type: str  # baseline, logistic, linear, cox, kaplan_meier, fine_gray
    data_path: str
    output_dir: str
    exposure_var: str
    outcome_var: str
    covariates: List[str] = field(default_factory=list)
    weight_var: str = "WTMEC2YR"
    psu_var: str = "SDMVPSU"
    strata_var: str = "SDMVSTRA"
    subgroup_var: Optional[str] = None
    time_var: Optional[str] = None
    event_var: Optional[str] = None
    competing_event: Optional[int] = None
    confidence_level: float = 0.95


class RScriptGenerator:
    """
    Survey-weighted R脚本生成器
    """

    # R包安装代码
    PACKAGES_INSTALL = """
# 自动安装缺失的R包
required_packages <- c(
  "survey", "tableone", "survival", "survminer",
  "ggplot2", "forestplot", "grid", "gridExtra",
  "broom", "dplyr", "tidyr", "readr", "writexl",
  "gtsummary", "flextable", "officer", "cmprsk",
  "tidycmprsk", "ggsci", "ggpubr", "Cairo"
)

for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org/", quiet = TRUE)
  }
}

# 加载所有包
suppressPackageStartupMessages({
  library(survey)
  library(tableone)
  library(survival)
  library(survminer)
  library(ggplot2)
  library(forestplot)
  library(grid)
  library(gridExtra)
  library(broom)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(gtsummary)
  library(flextable)
  library(officer)
  library(ggsci)
  library(ggpubr)
})
"""

    def __init__(self):
        pass

    def _preamble(self, config: AnalysisConfig) -> str:
        """生成脚本头部"""
        return f"""
# ============================================================
# NHANES Survey-Weighted Analysis
# Generated by NHANES-to-Lancet Platform
# Analysis: {config.analysis_type}
# Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# ============================================================

{self.PACKAGES_INSTALL}

# 加载数据
data <- read.csv("{config.data_path}")
cat("数据加载完成:", nrow(data), "行,", ncol(data), "列\\n")

# ============================================================
# 声明复杂调查设计 (Complex Survey Design)
# ============================================================
# NHANES使用分层多阶段概率抽样设计
# SDMVPSU: 伪初级抽样单元 (Primary Sampling Unit)
# SDMVSTRA: 伪分层变量 (Stratum)
# WTMEC2YR: 2年MEC检查权重 (Examination Weight)

nhanes_design <- svydesign(
  id = ~{config.psu_var},
  strata = ~{config.strata_var},
  weights = ~{config.weight_var},
  data = data,
  nest = TRUE
)

cat("调查设计声明完成\\n")
cat("有效样本量 (unweighted):", nrow(data), "\\n")
cat("加权总人数 (weighted):", round(sum(data${config.weight_var}), 0), "\\n\\n")
"""

    def generate_baseline_table(self, config: AnalysisConfig) -> str:
        """
        生成加权基线特征表 (Table 1)

        输出: Word文档 + CSV
        """
        vars_str = ", ".join([f'"{v}"' for v in config.covariates])
        categorical_vars = self._guess_categorical(config.covariates)
        cat_vars_str = ", ".join([f'"{v}"' for v in categorical_vars])

        script = self._preamble(config)
        script += f"""
# ============================================================
# Table 1: 加权基线特征表 (Weighted Baseline Characteristics)
# ============================================================

# 需要展示的变量
table_vars <- c({vars_str})

# 分类变量
cat_vars <- c({cat_vars_str})

# 连续变量
cont_vars <- setdiff(table_vars, cat_vars)

# 方法1: 使用tableone包 (支持调查权重)
cat("\\n--- 生成加权基线特征表 ---\\n")

# 创建加权基线表
baseline_table <- svyCreateTableOne(
  vars = table_vars,
  strata = "{config.exposure_var}",
  data = nhanes_design,
  factorVars = cat_vars,
  test = TRUE,
  addOverall = TRUE
)

# 打印控制台预览
print(baseline_table, showAllLevels = TRUE, smd = TRUE)

# 保存为CSV
baseline_df <- print(baseline_table, showAllLevels = TRUE, smd = TRUE,
                     exact = cat_vars, nonnormal = NULL,
                     formatOptions = list(big.mark = ","),
                     quote = FALSE, noSpaces = TRUE)
write.csv(baseline_df, file.path("{config.output_dir}", "table1_baseline.csv"))

# 方法2: 使用gtsummary包生成出版级表格
cat("\\n--- 生成Lancet标准表格 ---\\n")

# 创建survey设计对象用于gtsummary
tbl_baseline <- nhanes_design %>%
  tbl_svysummary(
    by = {f'"{config.exposure_var}"' if config.exposure_var else "NULL"},
    include = all_of(table_vars),
    statistic = list(
      all_continuous() ~ "{{mean}} ({{sd}})",
      all_categorical() ~ "{{n}} ({{p}}%)"
    ),
    label = list(
      # 变量标签可以在这里添加
    ),
    missing = "ifany",
    percent = "column"
  ) %>%
  add_p(
    test = list(
      all_continuous() ~ "svy.wilcox.test",
      all_categorical() ~ "svy.chisq.test"
    )
  ) %>%
  add_overall() %>%
  add_n() %>%
  bold_p() %>%
  modify_header(label = "**Variable**") %>%
  modify_spanning_header(
    all_stat_cols() ~ "**Weighted Baseline Characteristics**"
  )

# 保存为flextable (Word文档)
ft_baseline <- as_flex_table(tbl_baseline)
doc <- read_docx()
doc <- body_add_flextable(doc, ft_baseline)
print(doc, target = file.path("{config.output_dir}", "table1_baseline.docx"))

# 保存为gtsummary对象 (RDS)
saveRDS(tbl_baseline, file.path("{config.output_dir}", "table1_baseline.rds"))

cat("基线特征表已保存\\n\\n")
"""
        return script

    def generate_logistic_regression(self, config: AnalysisConfig) -> str:
        """
        生成加权Logistic回归分析

        输出: OR表 + 森林图
        """
        covariates_formula = " + ".join(config.covariates)
        all_vars = [config.exposure_var] + config.covariates
        vars_str = ", ".join([f'"{v}"' for v in all_vars])

        script = self._preamble(config)
        script += f"""
# ============================================================
# 加权Logistic回归 (Survey-Weighted Logistic Regression)
# ============================================================

cat("\\n--- 加权Logistic回归分析 ---\\n")

# 模型1: 粗模型 (Crude Model)
formula_crude <- as.formula("{config.outcome_var} ~ {config.exposure_var}")
model_crude <- svyglm(formula_crude, design = nhanes_design, family = quasibinomial())
cat("\\n=== 粗模型 (Model 1: Crude) ===\\n")
print(summary(model_crude))

# 模型2: 调整人口学变量
formula_model2 <- as.formula("{config.outcome_var} ~ {config.exposure_var} + RIAGENDR + RIDAGEYR")
model_2 <- svyglm(formula_model2, design = nhanes_design, family = quasibinomial())
cat("\\n=== 模型2: 调整年龄性别 ===\\n")
print(summary(model_2))

# 模型3: 完全调整模型
formula_full <- as.formula("{config.outcome_var} ~ {config.exposure_var} + {covariates_formula}")
model_full <- svyglm(formula_full, design = nhanes_design, family = quasibinomial())
cat("\\n=== 模型3: 完全调整模型 ===\\n")
print(summary(model_full))

# ============================================================
# 提取OR值和95%CI
# ============================================================

extract_or_table <- function(model, model_name) {{
  tidy_result <- tidy(model, exponentiate = TRUE, conf.int = TRUE)
  tidy_result$model <- model_name
  tidy_result$OR_CI <- sprintf("%.2f (%.2f-%.2f)", tidy_result$estimate, tidy_result$conf.low, tidy_result$conf.high)
  return(tidy_result)
}}

or_crude <- extract_or_table(model_crude, "Model 1 (Crude)")
or_model2 <- extract_or_table(model_2, "Model 2 (Age+Sex)")
or_full <- extract_or_table(model_full, "Model 3 (Fully Adjusted)")

# 合并结果
or_combined <- bind_rows(or_crude, or_model2, or_full)

# 筛选暴露变量的结果
or_exposure <- or_combined %>%
  filter(term == "{config.exposure_var}") %>%
  select(model, estimate, conf.low, conf.high, p.value, OR_CI)

cat("\\n=== 暴露变量的OR值 ===\\n")
print(or_exposure)

# 保存结果
write.csv(or_combined, file.path("{config.output_dir}", "logistic_regression_results.csv"), row.names = FALSE)
write.csv(or_exposure, file.path("{config.output_dir}", "logistic_regression_exposure_OR.csv"), row.names = FALSE)

# ============================================================
# 生成森林图 (Forest Plot)
# ============================================================

cat("\\n--- 生成森林图 ---\\n")

# 准备森林图数据
forest_data <- data.frame(
  Model = or_exposure$model,
  OR = or_exposure$estimate,
  Lower = or_exposure$conf.low,
  Upper = or_exposure$conf.high,
  P = or_exposure$p.value
)

# 生成森林图
png(file.path("{config.output_dir}", "forest_plot_logistic.png"), width = 1000, height = 500, res = 150)
forestplot(
  labeltext = cbind(
    as.character(forest_data$Model),
    sprintf("%.2f (%.2f-%.2f)", forest_data$OR, forest_data$Lower, forest_data$Upper),
    sprintf("%.3f", forest_data$P)
  ),
  mean = forest_data$OR,
  lower = forest_data$Lower,
  upper = forest_data$Upper,
  is.summary = c(FALSE, FALSE, TRUE),
  xlog = TRUE,
  xlab = "Odds Ratio (95% CI)",
  hrzl_lines = list("1" = gpar(lwd = 2)),
  txt_gp = fpTxtGp(
    label = gpar(cex = 0.9),
    ticks = gpar(cex = 0.8),
    xlab = gpar(cex = 0.9)
  ),
  col = fpColors(box = "darkblue", line = "darkblue", summary = "darkred"),
  title = "Association: {config.exposure_var} and {config.outcome_var}"
)
dev.off()

# 使用ggplot2生成更美观的森林图
p_forest <- ggplot(forest_data, aes(x = OR, y = reorder(Model, -OR))) +
  geom_point(size = 3, color = "#A51C30") +
  geom_errorbarh(aes(xmin = Lower, xmax = Upper), height = 0.2, color = "#A51C30") +
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray50") +
  scale_x_log10() +
  labs(
    title = "Association between {config.exposure_var} and {config.outcome_var}",
    x = "Odds Ratio (95% CI)",
    y = ""
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 12),
    axis.text = element_text(size = 10),
    panel.grid.minor = element_blank()
  )

ggsave(file.path("{config.output_dir}", "forest_plot_ggplot.png"), p_forest, width = 8, height = 4, dpi = 300)

cat("Logistic回归分析完成\\n\\n")
"""
        return script

    def generate_linear_regression(self, config: AnalysisConfig) -> str:
        """
        生成加权线性回归分析

        输出: Beta系数表
        """
        covariates_formula = " + ".join(config.covariates)

        script = self._preamble(config)
        script += f"""
# ============================================================
# 加权线性回归 (Survey-Weighted Linear Regression)
# ============================================================

cat("\\n--- 加权线性回归分析 ---\\n")

# 模型1: 粗模型
formula_crude <- as.formula("{config.outcome_var} ~ {config.exposure_var}")
model_crude <- svyglm(formula_crude, design = nhanes_design)
cat("\\n=== 粗模型 (Crude) ===\\n")
print(summary(model_crude))

# 模型2: 调整年龄性别
formula_model2 <- as.formula("{config.outcome_var} ~ {config.exposure_var} + RIAGENDR + RIDAGEYR")
model_2 <- svyglm(formula_model2, design = nhanes_design)
cat("\\n=== 模型2 (Age+Sex) ===\\n")
print(summary(model_2))

# 模型3: 完全调整模型
formula_full <- as.formula("{config.outcome_var} ~ {config.exposure_var} + {covariates_formula}")
model_full <- svyglm(formula_full, design = nhanes_design)
cat("\\n=== 模型3 (Fully Adjusted) ===\\n")
print(summary(model_full))

# 提取结果
extract_beta <- function(model, model_name) {{
  result <- tidy(model, conf.int = TRUE)
  result$model <- model_name
  result$Beta_CI <- sprintf("%.2f (%.2f-%.2f)", result$estimate, result$conf.low, result$conf.high)
  return(result)
}}

beta_combined <- bind_rows(
  extract_beta(model_crude, "Model 1 (Crude)"),
  extract_beta(model_2, "Model 2 (Age+Sex)"),
  extract_beta(model_full, "Model 3 (Fully Adjusted)")
)

write.csv(beta_combined, file.path("{config.output_dir}", "linear_regression_results.csv"), row.names = FALSE)

cat("线性回归分析完成\\n\\n")
"""
        return script

    def generate_kaplan_meier(self, config: AnalysisConfig) -> str:
        """
        生成加权Kaplan-Meier生存分析

        输出: 生存曲线图 + Log-rank检验
        """
        script = self._preamble(config)
        script += f"""
# ============================================================
# 加权Kaplan-Meier生存分析
# ============================================================

cat("\\n--- Kaplan-Meier生存分析 ---\\n")

# 创建生存对象
surv_obj <- Surv(time = data${config.time_var}, event = data${config.event_var})

# 非加权KM分析 (用于可视化)
km_fit <- survfit(surv_obj ~ data${config.exposure_var}, data = data)

# Log-rank检验
logrank_test <- survdiff(surv_obj ~ data${config.exposure_var}, data = data)
cat("\\n=== Log-rank检验 ===\\n")
print(logrank_test)
p_value <- 1 - pchisq(logrank_test$chisq, length(logrank_test$n) - 1)
cat("Log-rank P值:", format.pval(p_value, digits = 3), "\\n")

# 生存曲线图
p_surv <- ggsurvplot(
  km_fit,
  data = data,
  pval = TRUE,
  pval.method = TRUE,
  conf.int = TRUE,
  risk.table = TRUE,
  risk.table.col = "strata",
  risk.table.height = 0.25,
  linetype = "solid",
  palette = c("#A51C30", "#00468B"),
  xlab = "Follow-up Time",
  ylab = "Survival Probability",
  title = "Kaplan-Meier Survival Curves",
  legend.title = "{config.exposure_var}",
  legend.labs = levels(as.factor(data${config.exposure_var})),
  ggtheme = theme_bw(),
  font.main = c(14, "bold"),
  font.x = c(12),
  font.y = c(12),
  font.tickslab = c(10)
)

# 保存图片
png(file.path("{config.output_dir}", "km_survival_curve.png"), width = 1000, height = 800, res = 150)
print(p_surv)
dev.off()

# 也保存为PDF
pdf(file.path("{config.output_dir}", "km_survival_curve.pdf"), width = 10, height = 8)
print(p_surv)
dev.off()

# 中位生存时间
cat("\\n=== 中位生存时间 ===\\n")
print(km_fit)

cat("Kaplan-Meier分析完成\\n\\n")
"""
        return script

    def generate_cox_regression(self, config: AnalysisConfig) -> str:
        """
        生成加权Cox回归分析

        输出: HR表 + 森林图
        """
        covariates_formula = " + ".join(config.covariates)

        script = self._preamble(config)
        script += f"""
# ============================================================
# 加权Cox比例风险回归
# ============================================================

cat("\\n--- Cox回归分析 ---\\n")

# 模型1: 粗模型
cox_crude <- coxph(
  Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var},
  data = data,
  weights = {config.weight_var}
)
cat("\\n=== 粗模型 (Crude) ===\\n")
print(summary(cox_crude))

# 模型2: 调整年龄性别
cox_model2 <- coxph(
  Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var} + RIAGENDR + RIDAGEYR,
  data = data,
  weights = {config.weight_var}
)
cat("\\n=== 模型2 (Age+Sex) ===\\n")
print(summary(cox_model2))

# 模型3: 完全调整模型
cox_full <- coxph(
  Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var} + {covariates_formula},
  data = data,
  weights = {config.weight_var}
)
cat("\\n=== 模型3 (Fully Adjusted) ===\\n")
print(summary(cox_full))

# 提取HR值
extract_hr <- function(model, model_name) {{
  result <- tidy(model, exponentiate = TRUE, conf.int = TRUE)
  result$model <- model_name
  result$HR_CI <- sprintf("%.2f (%.2f-%.2f)", result$estimate, result$conf.low, result$conf.high)
  return(result)
}}

hr_combined <- bind_rows(
  extract_hr(cox_crude, "Model 1 (Crude)"),
  extract_hr(cox_model2, "Model 2 (Age+Sex)"),
  extract_hr(cox_full, "Model 3 (Fully Adjusted)")
)

# 保存HR表
write.csv(hr_combined, file.path("{config.output_dir}", "cox_regression_results.csv"), row.names = FALSE)

# 暴露变量的HR
hr_exposure <- hr_combined %>%
  filter(term == "{config.exposure_var}")

cat("\\n=== 暴露变量的HR ===\\n")
print(hr_exposure)

# 森林图
forest_data <- data.frame(
  Model = hr_exposure$model,
  HR = hr_exposure$estimate,
  Lower = hr_exposure$conf.low,
  Upper = hr_exposure$conf.high,
  P = hr_exposure$p.value
)

png(file.path("{config.output_dir}", "forest_plot_cox.png"), width = 1000, height = 500, res = 150)
forestplot(
  labeltext = cbind(
    as.character(forest_data$Model),
    sprintf("%.2f (%.2f-%.2f)", forest_data$HR, forest_data$Lower, forest_data$Upper),
    sprintf("%.3f", forest_data$P)
  ),
  mean = forest_data$HR,
  lower = forest_data$Lower,
  upper = forest_data$Upper,
  is.summary = c(FALSE, FALSE, TRUE),
  xlog = TRUE,
  xlab = "Hazard Ratio (95% CI)",
  col = fpColors(box = "#A51C30", line = "#A51C30", summary = "#00468B"),
  title = "Cox Regression: {config.exposure_var} and {config.outcome_var}"
)
dev.off()

# Cox模型假设检验 (比例风险假设)
cat("\\n=== 比例风险假设检验 (Schoenfeld残差) ===\\n")
ph_test <- cox.zph(cox_full)
print(ph_test)

png(file.path("{config.output_dir}", "cox_ph_assumption.png"), width = 1000, height = 800, res = 150)
par(mfrow = c(2, 2))
plot(ph_test)
dev.off()

cat("Cox回归分析完成\\n\\n")
"""
        return script

    def generate_subgroup_analysis(self, config: AnalysisConfig) -> str:
        """
        生成亚组分析 + 交互效应检验
        """
        covariates_formula = " + ".join(config.covariates)

        script = f"""
# ============================================================
# 亚组分析 (Subgroup Analysis)
# ============================================================

cat("\\n--- 亚组分析 ---\\n")

# 亚组变量: {config.subgroup_var}
subgroup_var <- "{config.subgroup_var}"
subgroup_levels <- unique(data[[subgroup_var]])
subgroup_levels <- subgroup_levels[!is.na(subgroup_levels)]

subgroup_results <- list()

for (level in subgroup_levels) {{
  subset_data <- data[data[[subgroup_var]] == level, ]

  # 创建子集的调查设计
  subset_design <- svydesign(
    id = ~{config.psu_var},
    strata = ~{config.strata_var},
    weights = ~{config.weight_var},
    data = subset_data,
    nest = TRUE
  )

  # 拟合模型
  formula_sub <- as.formula("{config.outcome_var} ~ {config.exposure_var} + {covariates_formula}")

  if ("{config.analysis_type}" %in% c("cox", "kaplan_meier")) {{
    model_sub <- coxph(
      Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var} + {covariates_formula},
      data = subset_data,
      weights = {config.weight_var}
    )
  }} else {{
    model_sub <- svyglm(formula_sub, design = subset_design, family = quasibinomial())
  }}

  result <- tidy(model_sub, exponentiate = TRUE, conf.int = TRUE)
  result$subgroup <- subgroup_var
  result$level <- as.character(level)
  result$n <- nrow(subset_data)
  subgroup_results[[as.character(level)]] <- result

  cat(sprintf("\\n亚组: %s = %s (n=%d)\\n", subgroup_var, level, nrow(subset_data)))
  print(result %>% filter(term == "{config.exposure_var}"))
}}

# 合并亚组结果
subgroup_combined <- bind_rows(subgroup_results)
subgroup_exposure <- subgroup_combined %>%
  filter(term == "{config.exposure_var}")

write.csv(subgroup_exposure, file.path("{config.output_dir}", "subgroup_analysis.csv"), row.names = FALSE)

# 亚组森林图
p_subgroup <- ggplot(subgroup_exposure, aes(x = estimate, y = reorder(level, -estimate))) +
  geom_point(size = 3, color = "#A51C30") +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2, color = "#A51C30") +
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray50") +
  scale_x_log10() +
  labs(
    title = paste("Subgroup Analysis by", subgroup_var),
    subtitle = paste("Exposure:", "{config.exposure_var}", "Outcome:", "{config.outcome_var}"),
    x = "Effect Size (95% CI)",
    y = subgroup_var
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"))

ggsave(file.path("{config.output_dir}", "subgroup_forest_plot.png"), p_subgroup, width = 8, height = 5, dpi = 300)

# ============================================================
# 交互效应检验
# ============================================================
cat("\\n--- 交互效应检验 ---\\n")

formula_interaction <- as.formula(
  "{config.outcome_var} ~ {config.exposure_var} * {subgroup_var} + {covariates_formula}"
)

if ("{config.analysis_type}" %in% c("cox", "kaplan_meier")) {{
  model_interaction <- coxph(
    Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var} * {subgroup_var} + {covariates_formula},
    data = data,
    weights = {config.weight_var}
  )
}} else {{
  model_interaction <- svyglm(formula_interaction, design = nhanes_design, family = quasibinomial())
}}

cat("\\n=== 交互效应模型 ===\\n")
print(summary(model_interaction))

interaction_term <- tidy(model_interaction) %>%
  filter(grepl(":", term))

cat("\\n=== 交互项P值 ===\\n")
print(interaction_term)
p_interaction <- interaction_term$p.value
cat(sprintf("\\n交互效应 P值: %.4f\\n", p_interaction))
cat(ifelse(p_interaction < 0.05,
  "交互效应显著 (P<0.05)，提示亚组间效应不同",
  "交互效应不显著 (P>=0.05)，提示亚组间效应一致\\n"))

cat("亚组分析完成\\n\\n")
"""
        return script

    def generate_sensitivity_analysis(self, config: AnalysisConfig) -> str:
        """
        生成敏感性分析

        包括:
        1. 排除前2年随访
        2. 多重插补
        3. 不同权重的比较
        """
        covariates_formula = " + ".join(config.covariates)

        script = f"""
# ============================================================
# 敏感性分析 (Sensitivity Analysis)
# ============================================================

cat("\\n--- 敏感性分析 ---\\n")

# 敏感性分析1: 排除前2年事件 (排除反向因果)
cat("\\n=== 敏感性分析1: 排除前2年事件 ===\\n")
data_sens1 <- data
if ("{config.time_var}" %in% names(data_sens1)) {{
  data_sens1$exclusion_flag <- ifelse(data_sens1${config.event_var} == 1 & data_sens1${config.time_var} < 2, 1, 0)
  data_sens1 <- data_sens1[data_sens1$exclusion_flag == 0 | is.na(data_sens1$exclusion_flag), ]
  cat("排除后样本量:", nrow(data_sens1), "\\n")
}}

design_sens1 <- svydesign(
  id = ~{config.psu_var}, strata = ~{config.strata_var},
  weights = ~{config.weight_var}, data = data_sens1, nest = TRUE
)

formula_sens <- as.formula("{config.outcome_var} ~ {config.exposure_var} + {covariates_formula}")

if ("{config.analysis_type}" == "cox") {{
  model_sens1 <- coxph(
    Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var} + {covariates_formula},
    data = data_sens1, weights = {config.weight_var}
  )
}} else {{
  model_sens1 <- svyglm(formula_sens, design = design_sens1, family = quasibinomial())
}}

cat("敏感性分析1结果:\\n")
print(tidy(model_sens1, exponentiate = TRUE, conf.int = TRUE) %>% filter(term == "{config.exposure_var}"))

# 敏感性分析2: 使用不同权重
cat("\\n=== 敏感性分析2: 使用Interview权重 ===\\n")
nhanes_design_int <- svydesign(
  id = ~SDMVPSU, strata = ~SDMVSTRA,
  weights = ~WTINT2YR, data = data, nest = TRUE
)

if ("{config.analysis_type}" == "cox") {{
  model_sens2 <- coxph(
    Surv({config.time_var}, {config.event_var}) ~ {config.exposure_var} + {covariates_formula},
    data = data, weights = WTINT2YR
  )
}} else {{
  model_sens2 <- svyglm(formula_sens, design = nhanes_design_int, family = quasibinomial())
}}

cat("敏感性分析2结果 (Interview Weight):\\n")
print(tidy(model_sens2, exponentiate = TRUE, conf.int = TRUE) %>% filter(term == "{config.exposure_var}"))

# 保存敏感性分析结果
sensitivity_results <- bind_rows(
  tidy(model_sens1, exponentiate = TRUE, conf.int = TRUE) %>%
    filter(term == "{config.exposure_var}") %>%
    mutate(analysis = "Exclude first 2 years"),
  tidy(model_sens2, exponentiate = TRUE, conf.int = TRUE) %>%
    filter(term == "{config.exposure_var}") %>%
    mutate(analysis = "Interview weight")
)

write.csv(sensitivity_results, file.path("{config.output_dir}", "sensitivity_analysis.csv"), row.names = FALSE)

cat("敏感性分析完成\\n\\n")
"""
        return script

    def generate_full_analysis(self, config: AnalysisConfig) -> str:
        """
        生成完整分析脚本 (根据analysis_type组合)
        """
        script = ""

        # 基线表 (所有分析类型都需要)
        script += self.generate_baseline_table(config)

        if config.analysis_type == "logistic":
            script += self.generate_logistic_regression(config)
        elif config.analysis_type == "linear":
            script += self.generate_linear_regression(config)
        elif config.analysis_type == "cox":
            script += self.generate_cox_regression(config)
        elif config.analysis_type == "kaplan_meier":
            script += self.generate_kaplan_meier(config)

        # 亚组分析 (如果有亚组变量)
        if config.subgroup_var:
            script += self.generate_subgroup_analysis(config)

        # 敏感性分析
        script += self.generate_sensitivity_analysis(config)

        # 结尾
        script += f"""
# ============================================================
# 分析完成汇总
# ============================================================

cat("\\n========================================\\n")
cat("NHANES Survey-Weighted Analysis Complete\\n")
cat("========================================\\n")
cat("分析类型: {config.analysis_type}\\n")
cat("暴露变量: {config.exposure_var}\\n")
cat("结局变量: {config.outcome_var}\\n")
cat("协变量: {', '.join(config.covariates)}\\n")
cat("调查权重: {config.weight_var}\\n")
cat("样本量 (unweighted):", nrow(data), "\\n")
cat("输出目录: {config.output_dir}\\n")
cat("========================================\\n")

# 列出生成的文件
output_files <- list.files("{config.output_dir}", full.names = TRUE)
cat("\\n生成的文件:\\n")
for (f in output_files) {{
  cat("  -", basename(f), "\\n")
}}

cat("\\n分析完成!\\n")
"""
        return script

    def _guess_categorical(self, variables: List[str]) -> List[str]:
        """猜测分类变量"""
        categorical = []
        for var in variables:
            if var in NHANES_VARIABLES:
                if NHANES_VARIABLES[var]["type"] == "categorical":
                    categorical.append(var)
            # 常见的分类变量模式
            elif var.startswith(("DIQ", "SMQ", "MCQ", "BPQ", "HUQ", "PAQ", "ALQ", "DBQ")):
                categorical.append(var)
        return categorical


# 导入变量字典
from . import NHANES_VARIABLES

# ============================================================
# 便捷函数
# ============================================================

def generate_analysis_script(
    analysis_type: str,
    data_path: str,
    output_dir: str,
    exposure_var: str,
    outcome_var: str,
    covariates: List[str],
    **kwargs
) -> str:
    """
    快速生成分析脚本

    Example:
        script = generate_analysis_script(
            analysis_type="logistic",
            data_path="./data/nhanes_data.csv",
            output_dir="./output/",
            exposure_var="BMXBMI",
            outcome_var="DIQ010",
            covariates=["RIDAGEYR", "RIAGENDR", "DMDEDUC2", "INDFMPIR"]
        )
    """
    config = AnalysisConfig(
        analysis_type=analysis_type,
        data_path=data_path,
        output_dir=output_dir,
        exposure_var=exposure_var,
        outcome_var=outcome_var,
        covariates=covariates,
        **kwargs
    )

    generator = RScriptGenerator()
    return generator.generate_full_analysis(config)
