"""
Survey-weighted R脚本生成器
NHANES复杂抽样设计统计分析
"""

from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field
from src.nhanes import NHANES_VARIABLES


@dataclass
class AnalysisConfig:
    analysis_type: str
    data_path: str
    output_dir: str
    exposure_var: str
    outcome_var: str
    covariates: List[str] = field(default_factory=list)
    weight_var: str = "WTMEC2YR"
    psu_var: str = "SDMVPSU"
    strata_var: str = "SDMVSTRA"
    subgroup_var: Optional[str] = None
    time_var: Optional[str] = None
    event_var: Optional[str] = None
    confidence_level: float = 0.95


class RScriptGenerator:
    PACKAGES_INSTALL = """
# 自动安装缺失的R包
required_packages <- c(
  "survey", "tableone", "survival", "survminer",
  "ggplot2", "forestplot", "grid", "gridExtra",
  "broom", "dplyr", "tidyr", "readr",
  "gtsummary", "flextable", "officer",
  "ggsci", "ggpubr"
)
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, repos = "https://cloud.r-project.org/", quiet = TRUE)
  }
}
suppressPackageStartupMessages({
  library(survey); library(tableone); library(survival); library(survminer)
  library(ggplot2); library(forestplot); library(grid); library(gridExtra)
  library(broom); library(dplyr); library(tidyr); library(readr)
  library(gtsummary); library(flextable); library(officer)
  library(ggsci); library(ggpubr)
})
"""

    def _preamble(self, config: AnalysisConfig) -> str:
        import datetime
        return f"""
# ============================================================
# NHANES Survey-Weighted Analysis
# Generated by NHANES-to-Lancet Platform
# Analysis: {config.analysis_type}
# Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# ============================================================

{self.PACKAGES_INSTALL}

data <- read.csv("{config.data_path}")
cat("数据加载完成:", nrow(data), "行,", ncol(data), "列\\n")

# 声明复杂调查设计 (Complex Survey Design)
nhanes_design <- svydesign(
  id = ~{config.psu_var}, strata = ~{config.strata_var},
  weights = ~{config.weight_var}, data = data, nest = TRUE
)
cat("调查设计声明完成, 有效样本量:", nrow(data), "\\n\\n")
"""

    def generate_baseline_table(self, config: AnalysisConfig) -> str:
        vars_str = ", ".join([f'"{v}"' for v in config.covariates])
        cat_vars = self._guess_categorical(config.covariates)
        cat_vars_str = ", ".join([f'"{v}"' for v in cat_vars])
        exposure = config.exposure_var if config.exposure_var else "NULL"

        return self._preamble(config) + f"""
# Table 1: 加权基线特征表
table_vars <- c({vars_str})
cat_vars <- c({cat_vars_str})

baseline_table <- svyCreateTableOne(
  vars = table_vars, strata = "{exposure}",
  data = nhanes_design, factorVars = cat_vars,
  test = TRUE, addOverall = TRUE
)
print(baseline_table, showAllLevels = TRUE, smd = TRUE)

baseline_df <- print(baseline_table, showAllLevels = TRUE, smd = TRUE,
                     exact = cat_vars, quote = FALSE, noSpaces = TRUE)
write.csv(baseline_df, file.path("{config.output_dir}", "table1_baseline.csv"))

# gtsummary版本
tbl_baseline <- nhanes_design %>%
  tbl_svysummary(
    by = "{exposure}", include = all_of(table_vars),
    statistic = list(all_continuous() ~ "{{mean}} ({{sd}})", all_categorical() ~ "{{n}} ({{p}}%)"),
    missing = "ifany", percent = "column"
  ) %>%
  add_p() %>% add_overall() %>% add_n() %>% bold_p()

ft <- as_flex_table(tbl_baseline)
doc <- read_docx()
doc <- body_add_flextable(doc, ft)
print(doc, target = file.path("{config.output_dir}", "table1_baseline.docx"))
cat("基线特征表已保存\\n\\n")
"""

    def generate_logistic_regression(self, config: AnalysisConfig) -> str:
        cov_formula = " + ".join(config.covariates)
        return self._preamble(config) + f"""
# 加权Logistic回归
cat("\\n--- 加权Logistic回归 ---\\n")

model_crude <- svyglm({config.outcome_var} ~ {config.exposure_var}, design = nhanes_design, family = quasibinomial())
model_2 <- svyglm({config.outcome_var} ~ {config.exposure_var} + RIAGENDR + RIDAGEYR, design = nhanes_design, family = quasibinomial())
model_full <- svyglm({config.outcome_var} ~ {config.exposure_var} + {cov_formula}, design = nhanes_design, family = quasibinomial())

extract_or <- function(model, name) {{
  r <- tidy(model, exponentiate = TRUE, conf.int = TRUE)
  r$model <- name
  r$OR_CI <- sprintf("%.2f (%.2f-%.2f)", r$estimate, r$conf.low, r$conf.high)
  return(r)
}}

or_all <- bind_rows(
  extract_or(model_crude, "Model 1 (Crude)"),
  extract_or(model_2, "Model 2 (Age+Sex)"),
  extract_or(model_full, "Model 3 (Fully Adjusted)")
)
write.csv(or_all, file.path("{config.output_dir}", "logistic_results.csv"), row.names = FALSE)

or_exp <- or_all %>% filter(term == "{config.exposure_var}")
cat("\\n暴露变量OR值:\\n"); print(or_exp)

# 森林图
forest_data <- data.frame(Model=or_exp$model, OR=or_exp$estimate, Lower=or_exp$conf.low, Upper=or_exp$conf.high)
png(file.path("{config.output_dir}", "forest_plot.png"), width=1000, height=500, res=150)
p <- ggplot(forest_data, aes(x=OR, y=reorder(Model,-OR))) +
  geom_point(size=3, color="#A51C30") +
  geom_errorbarh(aes(xmin=Lower, xmax=Upper), height=0.2, color="#A51C30") +
  geom_vline(xintercept=1, linetype="dashed", color="gray50") +
  scale_x_log10() + labs(title="Association: {config.exposure_var} → {config.outcome_var}", x="OR (95% CI)", y="") +
  theme_minimal()
print(p)
dev.off()
cat("Logistic回归完成\\n\\n")
"""

    def generate_linear_regression(self, config: AnalysisConfig) -> str:
        cov_formula = " + ".join(config.covariates)
        return self._preamble(config) + f"""
# 加权线性回归
model_crude <- svyglm({config.outcome_var} ~ {config.exposure_var}, design = nhanes_design)
model_full <- svyglm({config.outcome_var} ~ {config.exposure_var} + {cov_formula}, design = nhanes_design)
results <- bind_rows(
  tidy(model_crude, conf.int=TRUE) %>% mutate(model="Crude"),
  tidy(model_full, conf.int=TRUE) %>% mutate(model="Fully Adjusted")
)
write.csv(results, file.path("{config.output_dir}", "linear_results.csv"), row.names = FALSE)
cat("线性回归完成\\n\\n")
"""

    def generate_cox_regression(self, config: AnalysisConfig) -> str:
        cov_formula = " + ".join(config.covariates)
        time_var = config.time_var or "follow_up_time"
        event_var = config.event_var or "event"
        return self._preamble(config) + f"""
# 加权Cox回归
cox_crude <- coxph(Surv({time_var}, {event_var}) ~ {config.exposure_var}, data=data, weights={config.weight_var})
cox_full <- coxph(Surv({time_var}, {event_var}) ~ {config.exposure_var} + {cov_formula}, data=data, weights={config.weight_var})

hr_all <- bind_rows(
  tidy(cox_crude, exponentiate=TRUE, conf.int=TRUE) %>% mutate(model="Crude"),
  tidy(cox_full, exponentiate=TRUE, conf.int=TRUE) %>% mutate(model="Fully Adjusted")
)
write.csv(hr_all, file.path("{config.output_dir}", "cox_results.csv"), row.names = FALSE)

# 森林图
hr_exp <- hr_all %>% filter(term == "{config.exposure_var}")
forest_data <- data.frame(Model=hr_exp$model, HR=hr_exp$estimate, Lower=hr_exp$conf.low, Upper=hr_exp$conf.high)
png(file.path("{config.output_dir}", "forest_plot_cox.png"), width=1000, height=500, res=150)
p <- ggplot(forest_data, aes(x=HR, y=reorder(Model,-HR))) +
  geom_point(size=3, color="#A51C30") +
  geom_errorbarh(aes(xmin=Lower, xmax=Upper), height=0.2, color="#A51C30") +
  geom_vline(xintercept=1, linetype="dashed") + scale_x_log10() +
  labs(title="Cox Regression", x="HR (95% CI)", y="") + theme_minimal()
print(p)
dev.off()
cat("Cox回归完成\\n\\n")
"""

    def generate_full_analysis(self, config: AnalysisConfig) -> str:
        script = self.generate_baseline_table(config)
        if config.analysis_type == "logistic":
            script += self.generate_logistic_regression(config)
        elif config.analysis_type == "linear":
            script += self.generate_linear_regression(config)
        elif config.analysis_type == "cox":
            script += self.generate_cox_regression(config)

        script += f"""
# ============================================================
cat("\\n分析完成!\\n")
cat("输出目录: {config.output_dir}\\n")
"""
        return script

    def _guess_categorical(self, variables: List[str]) -> List[str]:
        cat = []
        for v in variables:
            if v in NHANES_VARIABLES and NHANES_VARIABLES[v]["type"] == "categorical":
                cat.append(v)
            elif v.startswith(("DIQ", "SMQ", "MCQ", "BPQ", "HUQ", "PAQ", "ALQ")):
                cat.append(v)
        return cat


def generate_analysis_script(analysis_type, data_path, output_dir, exposure_var, outcome_var, covariates, **kwargs) -> str:
    config = AnalysisConfig(
        analysis_type=analysis_type, data_path=data_path, output_dir=output_dir,
        exposure_var=exposure_var, outcome_var=outcome_var, covariates=covariates, **kwargs
    )
    return RScriptGenerator().generate_full_analysis(config)
